export const images = {
    stars: require("../images/stars.png"),
    thumnail: require("../images/thumnail.png"),
    logo: require("../images/logo.png"),
    xe : require("../images/xe.png"),
    avatar2: require("../images/avatar2.png"),
    avatar3: require("../images/avatar3.png"),
    avatar4: require("../images/avatar4.png"),
    logo2: require("../images/logo2.png"),
    logo3: require("../images/logo3.png"),
    logoNike: require("../images/logoNike.png"),
    nike2: require("../images/giay2.png"),
    nike3: require("../images/giay3.png"),
    cr7: require("../images/cr7.png"),
    messi: require("../images/messi.png"),
    logoCr7: require("../images/logoCr7.png"),
    logoMessi: require("../images/logoMessi.png"),
}
