export const icons = {
  logo: require('../icons/logo.png'),
  backup: require('../icons/backup.png'),
  tick: require('../icons/tick.png'),
  frame: require('../icons/Frame.png'),
  planet: require('../icons/planet.png'),
  ic_tag: require('../icons/ic_tag.png'),
  logo_vnpic: require('../icons/logo_vnpic.png'),
  ic_camera: require('../icons/ic_camera.png'),
  ic_gallery: require('../icons/ic_gallery.png'),
  ic_edit: require('../icons/ic_edit.png'),
  ic_report: require('../icons/ic_report.png'),
  ic_remove: require('../icons/ic_remove.png'),
  ic_nocomment: require('../icons/ic_nocomment.png'),
  ic_send: require('../icons/ic_send.png'),
};
